In [1]:
sentences = ["I ate dinner.", 
       "We had a three-course meal.", 
       "Brad came to dinner with us.",
       "He loves fish tacos.",
       "In the end, we all felt like we ate too much.",
       "We all agreed; it was a magnificent evening."]

1. Sentence transformer
2. langchain hugging
3. transformer

In [3]:
from sentence_transformers import SentenceTransformer

In [4]:
model = SentenceTransformer("all-mpnet-base-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\sowmy\anaconda3\envs\nlp\lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sowmy\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [5]:
sentences[0]

'I ate dinner.'

In [6]:
model.encode(sentences[0])

array([-1.58598050e-02,  4.59826030e-02, -1.46349613e-02, -4.85908799e-02,
       -3.60320951e-03,  3.17664333e-02, -3.27772461e-02,  2.11894922e-02,
        1.07366564e-02,  2.50182319e-02,  1.58237815e-02,  1.24070067e-02,
        1.62089821e-02, -1.30434548e-02,  4.58447039e-02,  4.40270118e-02,
        4.57802005e-02, -4.32260195e-03,  1.87806562e-02,  5.22198621e-03,
       -1.86415650e-02, -7.11806398e-03,  3.01359445e-02,  1.70695893e-02,
       -1.53764142e-02,  3.34172137e-02, -6.55884296e-03,  1.58591773e-02,
        1.37039516e-02, -2.02767309e-02,  3.26631963e-02,  5.48364175e-03,
       -3.53351049e-02, -1.06665194e-01,  1.85711565e-06,  3.66638824e-02,
       -1.71336029e-02,  3.34468447e-02, -6.43022135e-02,  6.90796599e-02,
        2.50845030e-02,  2.89430637e-02, -8.98415036e-03, -1.84546802e-02,
        2.81151999e-02, -2.34797373e-02,  1.21612530e-02,  6.25150204e-02,
       -8.58704001e-02, -1.84622966e-03,  7.95864500e-03, -8.42522830e-02,
       -2.26104185e-02,  

In [7]:
model.encode(sentences[0]).shape

(768,)

In [8]:
from langchain.embeddings import HuggingFaceEmbeddings

In [9]:
embedding_model_name = "sentence-transformers/all-mpnet-base-v2"

model_kwargs = {"device": "cpu"}
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name, model_kwargs=model_kwargs)

In [13]:
embedded_vector = embeddings.embed_query(sentences[0])

In [14]:
len(embedded_vector)

768

#### one more approach with transformer huggingface lib

In [15]:
import torch
from transformers import BertTokenizer, BertModel
import random

In [16]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

In [17]:
model = BertModel.from_pretrained("bert-base-uncased")

In [18]:
text = "follow my channel for genai learning"

In [19]:
encoding = tokenizer.batch_encode_plus([text], truncation=True, return_tensors="pt", add_special_tokens=True)

In [20]:
encoding

{'input_ids': tensor([[ 101, 3582, 2026, 3149, 2005, 8991, 4886, 4083,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [25]:
input_ids = encoding['input_ids']

In [26]:
attention_mask = encoding["attention_mask"]

In [28]:
with torch.no_grad():
    outputs = model(input_ids, attention_mask)
    word_embeddings = outputs.last_hidden_state

In [29]:
word_embeddings

tensor([[[ 0.0417,  0.0226,  0.0016,  ..., -0.1186, -0.0239,  0.3513],
         [ 0.7839,  0.0215,  0.3999,  ...,  0.4065,  0.2250, -0.2343],
         [ 0.3760, -0.4246,  0.3021,  ...,  0.0312, -0.1804,  0.0696],
         ...,
         [ 0.0892, -0.3312, -0.3764,  ..., -0.0863, -0.3077, -0.5731],
         [-0.5617, -0.6647, -0.2033,  ...,  0.7834, -0.0545, -0.2510],
         [ 1.0018,  0.1875, -0.2772,  ...,  0.1994, -0.8168, -0.0450]]])

In [34]:
word_embeddings.shape

torch.Size([1, 9, 768])

In [53]:
tokenizer.decode(input_ids[0], skip_special_tokens=True)

'follow my channel for genai learning'

In [87]:
text1 = "I am a good girl"
text2 = "I am a bad girl"

In [88]:
embedding1 = tokenizer.batch_encode_plus([text1], truncation=True, padding="max_length", return_tensors="pt", max_length=128)
embedding2 = tokenizer.batch_encode_plus([text2], truncation=True, padding="max_length", return_tensors="pt", max_length=128)

In [89]:
with torch.no_grad():
    outputs1 = model(embedding1['input_ids'], embedding1['attention_mask'])
    outputs2 = model(embedding2['input_ids'], embedding1['attention_mask'])
    
    word_embeddings1 = outputs1.last_hidden_state
    word_embeddings2 = outputs2.last_hidden_state

In [90]:
outputs1.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

In [91]:
word_embeddings2

tensor([[[-0.1497,  0.3252, -0.2012,  ..., -0.0692,  0.3319,  0.2653],
         [-0.0332,  0.1289, -0.6799,  ...,  0.0271,  0.9485,  0.3232],
         [-0.0770,  0.2348, -0.5834,  ..., -0.3631,  0.3777,  0.1340],
         ...,
         [ 0.0016,  0.0967,  0.2287,  ...,  0.2376,  0.0585, -0.0473],
         [-0.0706,  0.0451,  0.2192,  ...,  0.2905,  0.1144, -0.0852],
         [-0.0876,  0.0692,  0.3152,  ...,  0.2343, -0.0018, -0.0667]]])

In [92]:
from sklearn.metrics.pairwise import cosine_similarity

In [94]:
cosine_similarity(word_embeddings1.reshape(1, -1), word_embeddings2.reshape(1, -1))

array([[0.94389665]], dtype=float32)